name: Build DotNetLightning and deploy to NuGet
on: push
jobs:
  build_and_deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Install wget
      run: sudo apt install -y wget
    - name: install .Net Core 2.1
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo add-apt-repository universe
        sudo apt install apt-transport-https
        sudo apt update
        sudo apt install dotnet-sdk-2.1
    - name: Fetch requisite libraries
      run: |
        cd $GITHUB_WORKSPACE/src/DotNetLightning.Core
        dotnet add package -v 0.0.5-joemphilips -s "https://www.myget.org/F/joemphilips/api/v3/index.json" Secp256k1.Native
    - name: Package
      run: |
        cd $GITHUB_WORKSPACE/src/DotNetLightning.Core
        dotnet pack -p:Configuration=Release -p:Version=1.1.0-date`date +%Y%m%d-%H%M`.git-`echo $GITHUB_SHA | cut -c 1-7`
    - name: install .Net Core 3.0
      run: |
        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo add-apt-repository universe
        sudo apt install apt-transport-https
        sudo apt update
        sudo apt install dotnet-sdk-3.0
    - name: Build whole solution
      run: |
        dotnet build -p:Configuration=Release
    - name: Run tests
      run: |
        dotnet test
    - name: Upload nuget
      run: |
        cd $GITHUB_WORKSPACE/src/DotNetLightning.Core
        if [ ${{ secrets.NUGET_API_KEY }} ] && [ $GITHUB_REF == "refs/heads/master" ]; then
            dotnet nuget push ./bin/Release/DotNetLightning.Core*.nupkg -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
        fi
