name: Build DotNetLightning and deploy to NuGet
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup ${{ matrix.dotnet }} .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Run tests (BouncyCastle)
      # we want to run only once.
      if: startsWith(matrix.os, 'ubuntu-18')
      run: |
        dotnet build tests/DotNetLightning.Core.Tests -p:BouncyCastle=True
        dotnet run --no-build --project tests/DotNetLightning.Core.Tests

    - name: Clean to prepare for NSec build
      run: |
        dotnet clean
    - name: Run core tests
      run: |
        dotnet run --project tests/DotNetLightning.Core.Tests
    - name: Run other tests
      run: |
        dotnet test

  build_old_mono:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |

        # The sed command below will insert the following lines into DotNetLightning.Core.fsproj:
        #
        # <PropertyGroup Condition="'$(BouncyCastle)'=='true'">
        #   <TargetFrameworks>netstandard2.0</TargetFrameworks>
        # </PropertyGroup>
        #
        # This makes sure we build for netstandard2.0 only in this step
        sed -i "7i\ \ <PropertyGroup Condition=\"'\$(BouncyCastle)'=='true'\">\n    <TargetFrameworks>netstandard2.0</TargetFrameworks>\n  </PropertyGroup>" src/DotNetLightning.Core/DotNetLightning.Core.fsproj

        DEBIAN_FRONTEND=noninteractive sudo apt install -y make curl mono-complete mono-xbuild fsharp

        wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt install -y apt-transport-https
        sudo apt update
        sudo apt install msbuild

        source /etc/os-release
        sudo apt install -y gnupg2 ca-certificates
        sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
        echo "deb https://download.mono-project.com/repo/ubuntu stable-$UBUNTU_CODENAME main" | sudo tee /etc/apt/sources.list.d/mono-official-stable.list
        sudo apt update
        DEBIAN_FRONTEND=noninteractive sudo apt install -y mono-devel fsharp nuget
        nuget restore src/ResultUtils/ResultUtils.fsproj
        nuget restore src/InternalBech32Encoder/InternalBech32Encoder.csproj
        nuget restore src/Macaroons/Macaroons.csproj
        nuget restore src/DotNetLightning.Core/DotNetLightning.Core.fsproj
        msbuild src/DotNetLightning.Core/DotNetLightning.Core.fsproj -p:BouncyCastle=True