name: Build DotNetLightning and deploy to NuGet
on: [push, pull_request]
jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest, windows-latest]
        dotnet: ['3.1.200']
      fail-fast: true
    steps:
    - uses: actions/checkout@v2
    - name: Setup ${{ matrix.dotnet }} .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}

    - name: Run tests (BouncyCastle)
      # we want to run only once.
      if: startsWith(matrix.os, 'ubuntu-18')
      run: |
        dotnet build tests/DotNetLightning.Core.Tests -p:BouncyCastle=True
        dotnet run --no-build --project tests/DotNetLightning.Core.Tests

    - name: Clean to prepare for NSec build
      run: |
        dotnet clean
    - name: Run core tests
      run: |
        dotnet run --project tests/DotNetLightning.Core.Tests
    - name: Run other tests
      run: |
        dotnet test

  build_old_mono:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: |
        DEBIAN_FRONTEND=noninteractive sudo apt-get install -y mono-complete mono-xbuild fsharp
        wget https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
        sudo dpkg -i packages-microsoft-prod.deb
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https
        sudo apt-get update -y
        sudo apt-get install -y dotnet-sdk-3.1
        dotnet restore src/DotNetLightning.Core/DotNetLightning.Core.fsproj
        dotnet msbuild src/DotNetLightning.Core/DotNetLightning.Core.fsproj